from lib.One import *

def test_reading_time_empty_string():
    text = ""
    assert estimate_reading_time(text) == "0 seconds"

def test_reading_time_100_words():
    text = "Gravida ornare. Scelerisque. Duis bibendum tristique volutpat dapibus ullamcorper inceptos dis. Habitasse suscipit elit erat interdum et dis eget dapibus taciti class amet mus montes etiam, curae; congue erat purus faucibus id, ligula dignissim rhoncus. Dictumst molestie orci elementum suspendisse mollis eget Tortor Dignissim ligula sem eros luctus. Mus posuere cum bibendum risus. Sapien donec. Netus sapien. Nisl. Laoreet, nam etiam sagittis facilisis id tellus enim ultrices nonummy. Nulla pulvinar amet iaculis a donec Sapien maecenas mauris. Fringilla inceptos orci cras pulvinar massa porttitor id. Ante adipiscing quisque massa cras ullamcorper condimentum at praesent, dapibus tempor elementum vitae at ornare."
    assert estimate_reading_time(text) == "30 seconds"

def test_reading_time_200_words():
    text = "Arcu montes porta euismod fermentum porta consequat lectus laoreet tortor. Elementum blandit, aenean nullam aliquet sociosqu eros condimentum. Eget, fermentum mus taciti ultricies. Lectus gravida ultrices fames semper mi primis nascetur senectus phasellus egestas auctor adipiscing suscipit facilisi dictumst blandit malesuada praesent. Malesuada, cras. Placerat ac diam id nullam porttitor eleifend vitae vivamus lacus conubia donec eget Varius etiam Euismod morbi nostra turpis ultricies porta pharetra sociosqu magna odio hymenaeos metus penatibus vitae duis, facilisis Elit mattis, euismod tincidunt duis potenti porta consectetuer euismod, praesent tristique semper turpis elementum pulvinar sodales cras in eros gravida gravida nostra eros tempor euismod dolor placerat posuere hymenaeos erat posuere non, per neque venenatis Phasellus sapien nulla adipiscing aliquet nulla faucibus vestibulum. Tristique ut conubia cubilia ultricies quis curae; fringilla est mollis ridiculus nisi. Mi libero fringilla vivamus molestie lobortis ad pretium augue. Sociosqu facilisi. Pretium pulvinar turpis volutpat molestie mattis etiam pede tellus tincidunt augue cursus urna vel placerat. Odio odio fermentum. Scelerisque, vulputate at ultrices netus. Semper cursus nascetur aenean in morbi aenean sagittis quis Nam nascetur porttitor quisque mus et odio cras feugiat tincidunt tortor pede Litora sem faucibus mauris et diam habitasse, nulla dis nisl potenti vulputate consectetuer semper in."
    assert estimate_reading_time(text) == "1 minute"

def test_reading_time_300_words():
    text = "Faucibus Urna donec suspendisse curae; ultrices torquent pede morbi litora metus primis egestas sit. Venenatis consectetuer mi. Sit. Sociis. Cras. Lacinia pellentesque ultrices sociosqu class luctus, fusce ad massa platea vestibulum turpis tincidunt nunc id etiam quis nascetur inceptos eget cubilia risus non augue praesent tempor. Natoque parturient sociosqu nibh. Volutpat. Vestibulum augue auctor ipsum aliquet sed integer vivamus iaculis aliquam lacinia fusce aliquam nisl cum hendrerit conubia faucibus augue velit gravida ridiculus ante vehicula etiam donec. Orci urna. Sed felis quis lacus cras praesent. Porta libero aliquet massa eleifend per curae; egestas leo. Leo, commodo hendrerit faucibus neque inceptos est justo gravida et et. Hendrerit montes massa natoque pharetra Magnis mi eu sagittis natoque nunc interdum imperdiet scelerisque habitant enim hac magnis interdum morbi pede praesent Fames accumsan mi penatibus eget justo etiam aenean eu tincidunt augue hymenaeos, cubilia amet conubia mattis pulvinar natoque cursus ipsum euismod varius. Duis. Mi nonummy nunc sapien nullam cubilia fusce elit Sodales est curabitur sociis. Suspendisse odio massa tellus sagittis pretium rutrum. Sollicitudin praesent leo interdum blandit vivamus, accumsan at neque fusce magna. Magnis. Fusce quam hac, feugiat. Congue porta placerat adipiscing pretium odio, neque accumsan donec habitant luctus luctus sagittis convallis nascetur cum tortor adipiscing aliquam duis justo tellus, est. Platea. Torquent. A nullam. Urna convallis suscipit. Lorem eu natoque id, hac nisl ut Sed odio cum eu ante, adipiscing suspendisse elementum, mattis elit hymenaeos habitasse sagittis netus sociis lorem sollicitudin porttitor velit netus orci. Gravida nibh iaculis. Etiam aliquam luctus ante augue luctus. Varius magnis ipsum quisque tempor, leo praesent suscipit nulla convallis libero, phasellus quam. Convallis a diam nisi pharetra vulputate est feugiat taciti. Duis erat. Eleifend cum suspendisse. Sit malesuada. Arcu quisque tristique habitant adipiscing justo. Dapibus ad, malesuada massa felis, curabitur gravida sagittis est venenatis, ac massa sed."
    assert estimate_reading_time(text) == "1 minute 30 seconds"